### ISSUE TITLE
Error: Unable to load code: Error in Development mode

### ISSUE THREAD

**Issue by scharbaux** [destefanis/design-lint#50]
Hi,

I’m having issues running my plugin locally in development.

The verbose I get in the console sheds no light on what the issue is.

the first `yarn install` verboses throws the following warnings:

```
❯ yarn
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/2] ⠐ fsevents
warning Error running install script for optional dependency: "/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@18.14.2 | darwin | arm64
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for \"/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/lib/binding/Release/node-v108-darwin-arm64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v108-darwin-arm64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v108-darwin-arm64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v108-darwin-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@18.14.2 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v108-darwin-arm64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.14.2 | darwin | arm64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.14.2 | darwin | arm64
gyp info find Python using Python version 3.9.6 found at \"/Applications/Xcode.app/Contents/Developer/usr/bin/python3\"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/scharbaux/.nvm/versions/node/v18.14.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/scharbaux/.nvm/versions/node/v18.14.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/scharbaux/Library/Caches/node-gyp/18.14.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/scharbaux/Library/Caches/node-gyp/18.14.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/scharbaux/.nvm/versions/node/v18.14.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/scharbaux/Library/Caches/node-gyp/18.14.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.14.2 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../nan/nan.h:2536:8: warning: 'SetAccessor' is deprecated: Do signature check in accessor [-Wdeprecated-declarations]
  tpl->SetAccessor(
       ^
/Users/scharbaux/Library/Caches/node-gyp/18.14.2/include/node/v8-template.h:837:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Do signature check in accessor\")
  ^
/Users/scharbaux/Library/Caches/node-gyp/18.14.2/include/node/v8config.h:460:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: error: no member named 'GetContents' in 'v8::ArrayBuffer'
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                  ~~~~~~~~^
1 warning and 1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/scharbaux/.nvm/versions/node/v18.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command \"/Users/scharbaux/.nvm/versions/node/v18.14.2/bin/node\" \"/Users/scharbaux/.nvm/versions/node/v18.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/lib/binding/Release/node-v108-darwin-arm64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/lib/binding/Release/node-v108-darwin-arm64\" \"--napi_version=8\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v108\"
gyp ERR! cwd /Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents
gyp ERR! node -v v18.14.2
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/scharbaux/.nvm/versions/node/v18.14.2/bin/node /Users/scharbaux/.nvm/versions/node/v18.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/lib/binding/Release/node-v108-darwin-arm64/fse.node --module_name=fse --module_path=/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/lib/binding/Release/node-v108-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 22.3.0
node-pre-gyp ERR! command \"/Users/scharbaux/.nvm/versions/node/v18.14.2/bin/node\" \"/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents
node-pre-gyp ERR! node -v v18.14.2
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/scharbaux/.nvm/versions/node/v18.14.2/bin/node /Users/scharbaux/.nvm/versions/node/v18.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/lib/binding/Release/node-v108-darwin-arm64/fse.node --module_name=fse --module_path=/Users/scharbaux/Documents/AgodaGit/ads-lint/node_modules/fsevents/lib/binding/Release/node-v108-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)"
✨  Done in 59.98s.
```

Note:
> I’ve had to add `export SET NODE_OPTIONS=--openssl-legacy-provider` to the `yarn build:watch` script command to allow it to build Webpack for `arm-64` M1 chips, instead of `x84-64` by default with node 18.

This is the error I’m getting when importing the plugin’s manifest and executing it In Development mode:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/2776611/223099353-0b898758-d82a-4f5e-a192-6731ced82b73.png">

I’ve looked at the minified files and couldn’t find much clarity besides a vague error message regarding the manifest, but it seem to work just fine on the Published version so I don’t think there should be anything missing there.

The issue seem to only happen on my M1 Max, but runs just fine on my M1 Pro. I’ve tried uninstalling Figma completely (using the available uninstall.sh on Figma’s website), I’ve completely removed nodejs and reinstalled cleanly with nvm, but the issue still persists, making it impossible for me to run the plugin on this machine... 🤷‍♂️

On the other hand, the New Plugin template (that creates 5 rectangles) generated through the Figma app does run just fine in development mode on this machine.

My dev env:
Apple M1 Max `Ventura 13.2.1`
node `v18.4.2`
yarn `v1.22.19`
xcode-select `v2396`

Any guidance on where I should be looking to debug this issue would be greatly appreciated. 🙏😄

**Comment by scharbaux** [comment]
Update since yesterday: I figured it out!! When I first installed Figma on this machine, I must have accidentally dismissed the Privacy Permission prompt… I went to System Settings > Privacy > Files and Folders > Figma and toggled Documents Folder.

![image](https://user-images.githubusercontent.com/2776611/223366289-5737739c-e9f4-4458-a662-3cfe9c4090f7.png)

After restarting Figma it magically worked as expected :sparkles::tada:
